[package]
name = "tiffy"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
env_logger = "0.11.5"
geotiff = { path = "geotiff" }
image = "0.25.5"
show-image = { version = "0.14.0", features = ["image"] }
